/**:
   ros__parameters:
      timer_period: 0.5

sailbot: #Namespace
   airmar: #Node
      ros__parameters:
         airmar_port: "/dev/ttyACM0"
         use_fake_data: true
   
   teensy:
      ros__parameters:
         teensy_port: "COM9"
         simulated: true

   radio:
      ros__parameters:
         simulated: true
         
   main_algo:
      ros__parameters:
         tacking_buffer: 15

   vectornav:
      ros__parameters:
         use_fake_data: true
