/**:
   ros__parameters:
      timer_period: 0.5

sailbot: #Namespace
   airmar: #Node
      ros__parameters:
         airmar_port: "/dev/ttyACM0"
         use_fake_data: false
   
   teensy:
      ros__parameters:
         teensy_port: "/dev/ttyS8"
         simulated: false
   computer_vision: 
      ros__parameters:
         video_source: 0 
         hsv_lower: [0, 120, 180]
         hsv_upper: [10, 160, 255] 
         detection_threshold: 100