/**:
   ros__parameters:
      timer_period: 0.5

sailbot: #Namespace
   teensy:
      ros__parameters:
         teensy_port: "/dev/serial/by-id/usb-Teensyduino_USB_Serial_15675220-if00"
         simulated: false

   vectornav:
      ros__parameters:
         vectornav_port: "/dev/serial/by-id/usb-FTDI_USB-RS232-WE_AV0LF3XT-if00-port0"
         simulated: false
   
   buoy_detection: 
      ros__parameters:
         hsv_lower: [0, 127, 63]
         hsv_upper: [20, 255, 255] 
         detection_threshold: 100
         use_fake_data: false
      
   radio:
      ros__parameters:
         simulated: true # NOTE: this needs to be true for now while radio is not working

   main_algo:
      ros__parameters:
         tacking_buffer: 10
         debug: True
   

