/**:
   ros__parameters:
      timer_period: 0.5

sailbot: #Namespace
   airmar: #Node
      ros__parameters:
         airmar_port: "/dev/ttyACM0"
         use_fake_data: true
   
   teensy:
      ros__parameters:
         teensy_port: "COM9"
         simulated: true

   radio:
      ros__parameters:
         simulated: true

   waypoint_service:
      ros__parameters:
         waypoints:
            - "65.473,232.01"
            - "71.471,129.326"
            - "81.099,86.541"

