/**:
   ros__parameters:
      timer_period: 0.5

sailbot: #Namespace
   airmar: #Node
      ros__parameters:
         airmar_port: "/dev/ttyACM0"
         use_fake_data: true
   
   teensy:
      ros__parameters:
         teensy_port: "/dev/ttyS8"
         simulated: false
