/**:
   ros__parameters:
      timer_period: 0.5

sailbot: #Namespace
   airmar: #Node
      ros__parameters:
         airmar_port: "/dev/ttyACM0"
   
   anemometer:
      ros__parameters:
         anemometer_port: "usb-Teensyduino_Triple_Serial_16089010-if00"
   
   servo:
      ros__parameters:
         sail_port: "/dev/serial/by-id/usb-Teensyduino_Triple_Serial_16089010-if02"
         tail_port: "/dev/serial/by-id/usb-Teensyduino_Triple_Serial_16089010-if04"
