# Waypoint.srv

# Request
string command   # Command: "get" or "set"
string argument  # Argument for "set" command; ignored for "get" command
---
# Response
string message   # Response message
bool success     # Success status
